name: sma
description: A new Flutter project.
version: 7.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  dio: ^3.0.9
  intl: "^0.16.1"
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.7
  sembast: ^2.4.7
  sentry: ^3.0.1
  flutter_bloc: ^6.0.2
  flutter_spinkit: "^4.1.2"
  font_awesome_flutter: ^8.8.1
  google_nav_bar: ^2.2.0
  url_launcher: ^5.4.2
  flutter_offline: ^0.3.0
  data_connection_checker: ^0.3.4
  rflutter_alert: ^1.0.3
  flutter_dotenv: ^2.1.0
  equatable: ^1.2.3
  uuid: ^2.2.0
  flutter_masked_text: ^0.8.0
  date_field: ^0.3.0
  shared_preferences: ^0.5.8
  csv: ^4.0.3
  file_picker: ^1.13.3
  firebase_core: ^0.5.0
   # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.0.0

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  test: ^1.15.3
  device_preview: ^0.4.8

  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default.jpg
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
